// <auto-generated />
using System;
using System.Collections.Generic;
using DunktonPublicLibrary.App.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DunktonPublicLibrary.App.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250308015007_StartFresh")]
    partial class StartFresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DunktonPublicLibrary.App.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Credentials", "DunktonPublicLibrary.App.Domain.Entities.Account.Credentials#Credentials", b1 =>
                        {
                            b1.Property<string>("PasswordHash")
                                .IsRequired()
                                .HasMaxLength(255)
                                .IsUnicode(false)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("PasswordHash");

                            b1.Property<string>("PasswordSalt")
                                .IsRequired()
                                .HasMaxLength(255)
                                .IsUnicode(false)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("PasswordSalt");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("varchar(16)")
                                .HasColumnName("Username");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Dates", "DunktonPublicLibrary.App.Domain.Entities.Account.Dates#DateStamps", b1 =>
                        {
                            b1.Property<DateTime>("CreateDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreateDate");

                            b1.Property<DateTime?>("UpdateDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("UpdateDate");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Names", "DunktonPublicLibrary.App.Domain.Entities.Account.Names#Names", b1 =>
                        {
                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("LastName");
                        });

                    b.HasKey("Id")
                        .HasName("PK_Account");

                    b.HasIndex("RoleId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("DunktonPublicLibrary.App.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK_Role");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DunktonPublicLibrary.App.Domain.Entities.Account", b =>
                {
                    b.HasOne("DunktonPublicLibrary.App.Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Account_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DunktonPublicLibrary.App.Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
